<a href="https://colab.research.google.com/github/Reconocimiento-de-patrones-UNQ/Clase1/blob/main/Clase_1_b.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Clase: Introducción a NumPy y Pandas para análisis de datos científicos

🎯 Objetivos

    Comprender qué es NumPy y qué ventajas tiene sobre las listas de Python.

    Aprender a crear, indexar y operar con arrays de NumPy.

    Comprender qué es Pandas y su utilidad para la manipulación de datos tabulares.

    Aprender a crear, explorar y manipular DataFrames y Series.

¿Qué es NumPy y qué ventajas tiene sobre las listas de Python?

NumPy es una biblioteca de Python para trabajar con vectores y matrices (arrays n-dimensionales) de forma eficiente.
Ventajas frente a listas de Python:

    Más rápido: las operaciones usan código en C.

    Menor uso de memoria.

    Operaciones vectorizadas: sumas, multiplicaciones, etc. sin bucles.

    Funciones matemáticas integradas.

    Manejo directo de datos en 2D y más dimensiones.

Bibliotecas que usan NumPy internamente:

    Pandas (análisis de datos)

    SciPy (cálculo científico)

    scikit-learn (machine learning)

    Matplotlib (gráficos)

    TensorFlow / PyTorch (en parte, en el backend)



##Ejemplos:

In [1]:
import numpy as np
np.array([1, 2, 3])



array([1, 2, 3])

In [ ]:
np.zeros((3, 3))


array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
np.arange(0, 10, 2)

array([0, 2, 4, 6, 8])

In [ ]:
np.linspace(1, 10,10 )

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

np.arange(start, stop, step)    
    Genera valores con paso fijo.

    El parámetro step define cuánto se suma en cada paso.

    El valor final no se incluye si no cae justo en el rango.


np.linspace(start, stop, num)

    Genera una cantidad fija de num valores, espaciados uniformemente.

    El valor final sí se incluye.

#Indexar arrays

In [ ]:
a = np.array([10, 20, 30, 40])
b = a[0]         # 10
c = a[1:3]       # [20 30]
print (b,c)



10 [20 30 40]


array([1, 3, 5])

In [ ]:
a = np.array([[1, 2], [3, 4], [5, 6]])
b = a[1, 1]      # 4
c = a[:, 0]      # [1 3 5] (primera columna)
print(b,c)


4 [1 3 5]


![Gráfico](/content/numpy_2D_slicing_diagram.jpg)